README.md
lendingbot.py

Toggling AutoRenew now shows progress
Added --setAutoRenew CL
Changed all indentation to tabs.

Toggling AutoRenew now shows progress

---

README.md
lendingbot.py

Added a calculation of the average lending rate for all active loans to the status line.
I can't test it with multiple currencies as I'm not lending, but I don't see a reason why it shouldn't work.

Added "Average Lending Rate" calculation to status line.

---

Logger.py
README.md
RingBuffer.py
lendingbot.py
www/lendingbot.html

Created a new logging option,  log to json file:
- status can be completely seen (including all coins)
- log size can be controlled
- can be parsed like in the lendingbot.html example

JSON Logger & web status page

---

lendingbot.py

Matching the description in README

Updated default gapbottom and gaptop

---

README.md
lendingbot.py

Increased default minDailyRate to 0.04
Corrected jsonFile path

Aligned README configuration and Default one.

---

lendingbot.py
www/lendingbot.html

this branch allow you to display performance of all your currencies lended.
It will create a row for each currency found in json file. if for any reason you won't display a currency, you can remove it from var currencies = [ at line 42

loop through all possible currencies

---

lendingbot.py

With this we can skip out on using a cfg file at all.
User can run the entire program using arguments (helps with automated programs with multiple users) without the need to have a cfg for each user.

Argument parsing

---

www/lendingbot.js

Replaced roundFloat with printFloat, now rounds and returns String with fixed precision.
Converted tabs to spaces.

fix display for number less than 100 satoshis

---

lendingbot.py
poloniex.py

Try to fix HTTP Error 521: Origin Down

---

poloniex.py

Just a small fix which converts the errors returned from the Poloniex API to an exception. This allows you to get a better understanding of what went wrong, instead of getting a dictionary exception when the bot tries to access the data.

Handle errors from Poloniex API.

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md

Add some guidelines for issues and pull requests

Add contributing guidelines

---

Logger.py

Fixes issue https://github.com/Mikadily/poloniexlendingbot/issues/134 where status function in Console Logger is missing a parameter.
Couldn't test myself.

HOTFIX: Fix wrong function declaration in Console Logger

---

www/lendingbot.js

Showing both of them just pollutes screen in case if they are equal.

Display both Lent Total and Lent Lendable only if they are different

---

docs/configuration.rst
www/lendingbot.html
www/lendingbot.js

Add option to control how effective rate is calculated. Also clean up JS formatting. 
- [n/a] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [n/a] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**

 Add option to control how effective rate is calculated 

---

modules/Lending.py

Closes #165
Bot will, on a per-currency basis, lower the spread if the higher spread would mean it would not be able to lend more than the minimum amount. 
Before:
```
Have .0025 coin set to 3 spread. 
Bot would make 3 offers of ~.000833 each below the minimum of .001
Assumed: Poloniex rounds up the first two offers to meet the minimum, then makes the third fail due to not meeting it. 
That is what I see the situation to be, if you have another idea feel free to help.
```
After:
```
Have .0025 coin set to 3 spread. 
Bot sees that ".0025 < .001 * 3" and so removes one spread.
Bot sees that it may now split .0025 by 2 and be over the minimum for both lends.
Two offers for .00125 are placed and accepted.
```
If you only have <.001 coin, the function would never be called in the first place, …

Lessen spread if can't meet minimum amount

---

default.cfg.example
docs/configuration.rst
modules/Lending.py

If a coin's market does not meet its mindailyrate, then it will wait instead of lending at min.
Closes #46

Hide coins if mindailyrate not met

---

lendingbot.py
modules/Poloniex.py

Fixed configuration issues mentioned in https://github.com/Mikadily/poloniexlendingbot/issues/91

Fix config issues

---

default.cfg.example
docs/configuration.rst
lendingbot.py
modules/Configuration.py
modules/Data.py
modules/Lending.py
modules/MarketAnalysis.py
modules/Poloniex.py

Goal: To overhaul the lending module that has become difficult to modify, will allow us to fine-tune its function in the future.
Made much of the creation of orders more direct.
Fixes #165 - This error was due to splitting a satoshi in half, and they both wanted to round up.
Fixes #180 - Poloniex minloansize was increased, bot now dynamically changes to any potential increases.
Fixes #188 - Governs max API requests per second
Fixes #192 - Chdir now checks for lendingbot.py instead of an accidentally deletable file
Fixes #195 - Bugfixes about coincfg settings and the like

Overhaul lending module

---

modules/MarketAnalysis.py

Fix MarketAnalysis getting stuck because of network errors.
Fixes Issue: https://github.com/Mikadily/poloniexlendingbot/issues/248
MarketAnalysis runs in it's own thread, before this commit any exception would make the thread exit.
Solution is to catch the exception and continue after the sleep.
in progrexx

Fix MarketAnalysis getting stuck because of network errors.

---

docs/configuration.rst
lendingbot.py

Handles more errors from Poloniex correctly, specifically HTTPError and URLError.
Fixes https://github.com/Mikadily/poloniexlendingbot/issues/251 and https://github.com/Mikadily/poloniexlendingbot/issues/257
Testing now

Catch all HTTP Errors

---

default.cfg.example
docs/configuration.rst
modules/Configuration.py
modules/Lending.py

Details are in this issue: https://github.com/Mikadily/poloniexlendingbot/issues/278
Working so far!

Fix notify_xday_threshold, implement notify_new_loans option #278

---

www/lendingbot.html
www/lendingbot.js

Fix navbar position when settings dialog opens

Fix navbar position when settings dialog opens

---

modules/Lending.py

Solves List indices must be integer Error when rate > max_daily_rate

---

README.md

Use icons instead of text links for Telegram and add Slack
- [N/A] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

Add Slack and Telegram badges

---

default.cfg.example
docs/configuration.rst
modules/Configuration.py
modules/Notify.py

* fixes the `To:` email header (without the patch it's rendered like this: `To: ['user@example.com']`)
* adds `email_smtp_starttls` configuration to connect to STARTTLS SMTP servers
* fixes a typo
It's been working as intended on a STARTTLS server.

Minor mail fixes

---

www/lendingbot.html
www/lendingbot.js

Old calculation would factor the lent percentage (lent/total) into the compound function, which led to lower yearly rate.
In progress.

Fix lentperc yearly calculation

---

docs/installation.rst

Updating the bot on Pythonanywhere.com

---

README.md

Mention which ones are more often used.
Also added mention of Docker
- [N/A] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [N/A] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

Reformat chats on Readme

---

modules/Poloniex.py

Closes #338  - extract error messages from returned content when an HTTP error occurs on the API
Has been running for over 24hrs.  Unfortunately the error that precipitated the change hasn't occurred again so the code block hasn't actually run in regular usage.
You can force the code block to run by changing the 1000 in `req['nonce'] = int(time.time() * 1000)` to 10.

improve error reporting on HTTP error

---

plugins/AccountStats.py

Change 24Hr earnings to Yesterday so its reliably comparable with reports. (https://github.com/BitBotFactory/poloniexlendingbot/issues/372)
Output earnings into json file, so they can be displayed in html or otherwise. 
(was mentioned somewhere)
Fix issue when user doesn't have any history (https://github.com/BitBotFactory/poloniexlendingbot/issues/363)
in progress

Fix AccountStats issues

---

modules/Lending.py

Fix spread lending in RawBTC mode
Running

Fix gapmode RawBTC

---

default.cfg.example

Update gaps to a more reasonable value, using the RawBTC method.

Update gaps in example

---

modules/Configuration.py

Fixed typo in error message output during parsing configuration file for the upper limit.
Fixes #419
Fully tested

Configuration file error log fix

---

modules/Bitfinex.py

This fixed issue: https://github.com/BitBotFactory/poloniexlendingbot/issues/459
Local bot works after implementing this change.
- [x ] Bug fix (non-breaking change which fixes an issue)

filter out unhandled account type

---

lendingbot.py

Add checking notify_caught_exception value

---

modules/Configuration.py

Fix KeyError: 'notify_caught_exception'

---

plugins/AccountStats.py

Fix issue #478 duplicate entries on Bitfinex
Implement AccountStats upgrade
Upgrade AccounStatsDB to version 2
Set id and currency as unique keys for the database
This change erases the current DB and fetches it from the exchange

Adjust AccountStats DB to support Bitfinex

---

modules/Bitfinex.py

Fix for issue https://github.com/BitBotFactory/poloniexlendingbot/issues/444
- x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [N/A ] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**

Fix 400 Bad Request

---

plugins/Charts.py

Using round makes it work on earlier versions
- [N/A] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

printf is only available in sqlite3>=3.8.3

---

modules/Bitfinex.py
modules/ExchangeApi.py
modules/MarketAnalysis.py
modules/Poloniex.py
tests/test_PoloniexAPI.py

Introduce a 60 req per min limit to Bitfinex API
Introduce a 60 req per min limit to Bitfinex API
Fixed some minor python coding issues
Should fix issue #458
Improve Poloniex error messages

Bitfinex & Poloniex api impr

---

modules/MarketAnalysis.py
tests/test_MarketAnalysis.py

Fixes the pandas issue of mapping to an axes that isn't the right size and some other unhandled errors when you receive some garbage data.
Completely new set of unit tests. Still missing a few things though. 

Market Analysis: Fix unhandled exceptions and rewrite/fix all unit tests

---

modules/Bitfinex.py

Reduce chances of nonce collisions

---

modules/MarketAnalysis.py

Closes #434
Also doesn't print a TB when returning loan offers unless ma_debug_log is turned on

Fix recorded data when no rate offers exist, don't print all tracebacks

---

modules/Logger.py
modules/Poloniex.py

It seems that as part of the Bitfinex refactoring an error was introduced that would make the bot crash and not recover.
Fix issue #544
Correct handle exception responses from cloudflare
Prevent Logger.writeJsonFile from crashing because of unicode issues
In Progress

Html response fix

---

default.cfg.example
docs/configuration.rst
modules/Configuration.py
modules/Lending.py

The "FRR Delta" is a dynamic rate that allows you to specify an offset to the Flash Return Rate. For example, if you specifiy a delta of -0.001, when the FRR is 0.045 your calculated rate will be 0.044. Once matched, the rate becomes static and will not update against FRR any more.
- [] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**

FRR Delta for Bitfinex

---

default.cfg.example
docs/configuration.rst
modules/Bitfinex.py
modules/Configuration.py
modules/Lending.py

Based on new Bitcoin Gold coin listing on Bitfinex, we receive the following error message:
Error API Error 400: {"message":"Unknown currency"} Requesting https://api.bitfinex.com/v1/lendbook/BTG?limit_asks=100&limit_bids=100
Caught API Error 400: {"message":"Unknown currency"} Requesting https://api.bitfinex.com/v1/lendbook/BTG?limit_asks=100&limit_bids=100 reading from exchange API, ignoring
The issue is that the coin is listing in Symbols but not in lending book. So, here you can find a solution for this bug. On the other side, I'm already missing a good blacklist feature, because this bot is requesting bitfinex api for coins which are not included in "all_currencies" (in config).
Ongoing

Added Blacklist Option

---

modules/Bitfinex.py

Discover minimum amount in EUR

---

modules/WebServer.py

Fix a possible security risk presented by path traversal.

---

modules/Configuration.py

Just that, only changed the value in line 125 in Configuration.py
- [x ] Bug fix (non-breaking change which fixes an issue)
- [N/A] New feature (non-breaking change which adds functionality)
- [N/A] Breaking change (fix or feature that would cause existing functionality to change)
- [Yes] **I have read CONTRIBUTING.md**
- [Somewhat] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [Yes] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [N/A] **I have updated the config file accordingly if my …

changed lower_limit according to updated Poloniex limits in Configuration.py

---

docker-compose.yaml

pandas stopped supporting python2... it'd be better to move the master to python3...

upgrade pandas

---

default.cfg.example
modules/Lending.py

Adjust maxPeriod from 30 to 120 days for Bitfinex according to Bitfinex
Closes #651 
Link to Bitfinex's Announcement: https://www.bitfinex.com/posts/557
Successfully tested with my bot

Adjust maxPeriod from 30 to 120 days for Bitfinex according to Bitfinex
