BitBotFactory/MikaLendingBot

- lendingbot.py
Nothing special, replaced "default.cnf" with "default.cfg".
> Fix spelling error in lendingbot.py

- lendingbot.py
- poloniex.py
returnOpenLoanOffers doesn't have any arguments.
Fixes Issue #54
> Matching returnOpenLoanOffers to the API

- ConsoleUtils.py
- Logger.py
The status line should be only one line.  Previously it had a fixed
width of 99 characters.  Now the width is set to the actual terminal
width.  This value is determined again every time the status line is
updated, so that a running lending bot can be accessed from terminals
with different widths, like in a tmux setup.
> Automatically adjust width of status line.

- www/lendingbot.html
- www/lendingbot.js
Current layout can not be displayed on mobile phone portrait view
without scrolling (320x... and 360x... resolutions) due to 5 rows. This
commit reduces maximum number of rows from 5 to 3 by combining
Active/Total coins and Average/Effective rate columns.
Other changes:
* Add yearly interest rate (with reinvestment and without). Can be used
to compare interest rate with bank offers.
* Display percentage of lent coins from total coins.
* Replace `container-fluid` with `container` to improve readability on
desktop screens.
> Make layout more mobile friendly

- README.md
- lendingbot.py
I have created a new version of my feature xDays. I have used this configuration for about a week. I copied the changes made to Github.
I'm not quite sure what I did. The script has evolved a bit since last time I used it. I just tried and tried until it was stable. I havn't observed any issues with it yet.
Feel free to look at it and see if it fits.
Old pull request: #8
> The legend of xDays is back!

- lendingbot.py
If a loan offer is taken some time in between the "returnOpenLoanOffers" and "cancelLoanOffer" calls, the attempt to cancel the order will raise an error since it's already taken.
When this happens, the uncaught exception propagates to the main loop and causes the bot to not lend out its funds for as long as sleepTime.
This issue will be more likely to occur the higher the "spreadLend" parameter is.
<pre>
2016-09-08 15:56:21 Canceling all BTC orders... Loan offer canceled.
2016-09-08 15:56:22 Canceling all BTC orders... Loan offer canceled.
2016-09-08 15:56:22 Canceling all BTC orders... Loan offer canceled.
2016-09-08 15:56:22 Canceling all BTC orders... Loan offer canceled.
2016-09-08 15:56:23 ERROR: Error canceling loan order, or you are not the person who placed it.
Traceback (most …
> Catch exception when attempting to cancel loan offer

- Logger.py
- README.md
- lendingbot.py
- www/lendingbot.js
I add the option to display the Account Estimated Earnings on BTC or in USD. The default is BTC.
> Add the option to display the Account Estimated Earnings on BTC or in USD

- .gitignore
- Logger.py
- README.md
- lendingbot.py
- www/lendingbot.js
I made the feature, to choose the amount or percent you want to lent. but it includes the changes on the #112
When I create this feature discover or create a bug that when you have balance not lent on Lending and is less than minLoanSize the bot make more than 6 api calls per second. I change that. Now if the activeBal is less than minLoanSize it update the totalCoins and skip to the next coin.
in the config is like that
```
#Max amount to lent. if set to 0 or commented the bot will check for maxpercenttolent.
#maxtolent = 0
#Max percent to lent. if set to 0 or commented the bot will lent the 100%.
#maxpercenttolent = 0
#Max to lent conditional rate. if set to more than 0 the maxtolent or maxpercenttolent will be used when then rate is less or equal to the maxtolentrate. if set to 0 or …
```
> Max to lent

- Logger.py
- default.cfg.example
- docs/configuration.rst
- lendingbot.py
Allows user to add a date on which the bot will make sure all lends are done by.
Counts down the days on webpage, then automatically shuts down once it can no longer lend.
For users who want the bot to be done by a certain date. Recommended to give it 60 day notice so you don't get stuck with any super long lends.
Closes issue #14 
Tested with endDate set in the past, not set at all, set in the far future, and set tomorrow. Bot performed as expected in all cases. Bot deactivates at the first attempt to lend after midnight two days before enddate and leaves a message on the webpage.
> Add End Date

- README.md
- default.cfg.example
- docs/configuration.rst
- lendingbot.py
As Poloniex added a button in their interface for toggling autorenew on all loans this feature isn't needed anymore, it was based on making multiple calls to their service and would take too long.
Removing this will reduce code complexity.
Tested
> Remove autorenew

- www/lendingbot.js
Fix issue described in https://github.com/Mikadily/poloniexlendingbot/issues/236
in progress
> fixed display of low values like 1e-7

- lendingbot.py
Polo sometimes return a bad error code we can't parse. This catches that exception. 
Fixes https://github.com/Mikadily/poloniexlendingbot/issues/205
Tested
> Catch the bad status line exception and log it

- default.cfg.example
- modules/Configuration.py
- modules/Lending.py
Disabled summary scheduler if Notifications aren't configured
Check if notifications are enabled before running the scheduler thread
> Disabled summary scheduler if notify_summary_minutes isn't configured

- modules/WebServer.py
This prevents the webserver from hanging on KeyboardInterrupt
When attempting to terminate the lending bot with the webserver running, the "Stopping WebServer" message printed and the process failed to terminate for many seconds, sometimes leading to a "Failed to stop WebServer:" message with a stack trace.
I'm open to suggestions of how to test this. It now exits cleanly for me, but I'm not sure how to add a good unit test for that.
The source for socketserver has the following comment:
```
def shutdown(self):
"""Stops the serve_forever loop.
Blocks until the loop has finished. This must be called while
serve_forever() is running in another thread, or it will
deadlock.
```
This change just follows through with that advice by sending the shutdown signal in a new thread specifically opened …
> Send TCPServer shutdown signal from a separate thread

- docs/configuration.rst
There was a copy-pasting mistake in the Analyse Currencies section.
> Fix parameter description

- www/lendingbot.html
- www/lendingbot.js
This makes the page update every 10 seconds instead of every 30. 
Currently testing this for 24hrs
- [~] New feature (non-breaking change which adds functionality)
> Web view improvements (update interval, settings)

- modules/Poloniex.py
- tests/test_PoloniexAPI.py
I've noticed that the 422 errors are related to making multiple calls in parallel to Poloniex API.
Additionally the limit_request_rate has an issue when used from multiple threads as it would only sleep the current thread.
Both issues are fixed and unit tested, synchronizing the calls might slow down the bot in some situations.
In progress.
> Synchronized Poloniex API Calls

- modules/Lending.py
Fix issue #301, restore gap calculation based on total coin balance.
In progress.
> calculate gapbottom and gaptop according to total balance

- default.cfg.example
- docs/configuration.rst
- modules/Configuration.py
- modules/Lending.py
Allows users to set a hard value to skip in the lendbook, as opposed to only offering values relative to their balance.
Has a `gapmode` setting that allows switching between `relative`, `raw`,  or `rawbtc` gaps (and possibly even add a setting that is relative to the market's volume?)
Closes #269
> Add Raw gap setting

- modules/Poloniex.py
@rnevet pointed out I was re-raising the wrong exception if Poloniex responded with a non-JSON response (in #365).  I fixed that, but also made it so the error message will contain whatever is in the response from Poloniex if it's not actually JSON or is JSON but doesn't contain a 'error' component.
- [n/a] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [n/a] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [n/a] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**
> fix and improve #365

- modules/Poloniex.py
dealing with issue commented on #390 ... The API seems to respond with a page of HTML when Cloudflare is not able to communicate with the backend.  It's unlikely to get any useful information from the content on a 502 error so we skip outputting that.
- [n/a] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [n/a] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [n/a] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**
> don't output large dump of html from Cloudflare on 502 Gateway Error

- modules/Lending.py
When a user does not have a gapMode set in their configuration the bot was trying to set some defaults for the gap mode and then get proper gap mode rates. It was calling the wrong function in this case and returning a dictionary instead of a list of decimal values. This caused the exception.
> Fixes #384

- modules/Logger.py
Closes #374 
Wrap messages in a .format to get around TypeErrors.
Could have changed more, but the logging module needs an overhaul in the future anyway.
Testing
> Put messages in a .format to stop TypeErrors

- modules/Bitfinex.py
In case of network or exchange problem, it's a possible that bot is hung during API request.
Adding timeout value fixed the hung problem.
Fixed issue #449 with bot hung during work with bitfinex.
Tested for a few days. No hungs was observed.
> Added timeout to API request for prevent hung

- default.cfg.example
- docs/configuration.rst
- lendingbot.py
- modules/Logger.py
- www/lendingbot.js
Bot usually start with name 'Lending bot'.
In case few instances of bot work at the same time it is useful to customize the name that allows identifying instance quickly.
Added configuration option '[BOT] label' that define the unique name of the bot instance. This name is used in html page and console logs.
This changes don't change bots behavior during work and could be verified during start-up
> Allow to change default bot name in html page

- modules/Bitfinex.py
Closes #483 
Returns all currencies the bot is configured for on Bitfinex when requested, even if the balance is 0. 
> Fix 'Incorrect coin entered for transferCurrencies' #483

- modules/Lending.py
Allowing bot to change the max daily lending rate percent, which is 7% on Bitfinex and 5% on Poloniex, depending on current exchange being used
tested for 24 hours + and executed at least one loan offer on Bitfinex
> Change min/max daily lend rate depending on exchange (and simplify xdays)

- default.cfg.example
- modules/Configuration.py
- modules/Notify.py
Adds the ability to set a Slack Username for the Bot notifications via a configuration value. This is a PR for #575. 
I've had these changes running for over 24 hours in my testing without issue.
> Addition of a Slack Username parameter as a configuration option.

- modules/Notify.py
the irc lib in use doesn't support sending multiline messages. this patch splits messages containing newline characters into multiple irc messgaes to resolve issue: https://github.com/BitBotFactory/poloniexlendingbot/issues/565
without patching, irc notifications just fail and throw an exception, when messages contain a newline
testing started at 2017-11-13 19:30:00 UTC
no exception thrown at startup (an exception is normally thrown without the patch)
> split multiline message into multiple irc messages

- docker-compose.yaml
Closes #574 
This new image has numpy and pandas already installed, this greatly improves start up time and allows it to be used on hosts that cannot compile numpy / pandas (Some Raspberry PI and some NAS devices)
> Use docker image with pandas and numpy already installed

- default.cfg.example
- docs/configuration.rst
- modules/Configuration.py
To reduce development effort we should maintain only one coin specific configuration as suggested in #364, as it seems that coinconfig is broken in latest version, I suggest removing it finally.
This sort of fixes https://github.com/BitBotFactory/poloniexlendingbot/issues/609 by telling the user to use the section config.
> remove coinconfig one line

- docs/installation.rst
Changing `lendingbot.service` permission and setting the command `sudo systemctl daemon-reload` before enable `lendingbot.service`
> [FIX/UPDATE] Setting permissions and commands
